services:
  tpv-ticket:
    build: .
    image: tpv-ticket:1.0.0
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/tpvticket?authSource=admin
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
      SPRING_SECURITY_OAUTH2_JWK-URI: http://host.docker.internal:8080/tpv-user/oauth2/jwks
      SPRING_SECURITY_OAUTH2_TOKEN-URI: http://host.docker.internal:8080/tpv-user/oauth2/token
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose -f docker-compose-dev.yml up --build -d

#> ports: -"0:8083" or remove
#> docker compose -f docker-compose-dev.yml -p tpv-tickets up --scale tpv-ticket=2 -d