server:
  port: 8082

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Local Mongodb database (local or Dockerized) -------------
spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/tpv?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
